### ISSUE TITLE
Implement Caching of REST Requests

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#1]
To achieve a more responsive presentation of the application, rest requests should be cached. This will achieve multiple benefits which will improve the overall application

**Comment by jyore** [comment]
I have two disk persistence strategies [filesystem and database] and a two stage cache written.  I am currently testing these classes.

They will map any key [String] value [Object] pair, providing a generic mechanism to handle anything that needs to be stored.

**Comment by jyore** [comment]
Caching libraries added in commit fa6c6d04832f54071bc4cebda1eb37cf281822dc

**Comment by jyore** [comment]
Proposed workflow for REST caching:

FOR HITS:
Open page --> Search two-stage cache --> display page --> REST call --> update cache --> update page

FOR MISSES:
Open page --> Search two-stage cache --> REST call --> update cache --> display page

@sabre1041 please comment on workflow

**Comment by jyore** [comment]
- Make TwoStageCache singleton (may need to remove the namespacing feature)
- Add put's in Processor 
- Add get's in activity

**Comment by jyore** [comment]
commit 15a5d8e6ec941ceecc67e97f1d144b7c5c66f442 changed TwoStageCache to singleton
