### ISSUE TITLE
Add ability to manage embedded cartridges

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#15]
Create the functionality to manage embedded cartridges within an application:
- Functionality similar to the list application page where each embedded cartridge on the application cartridges page would have the ability to be "long selected"  which would open a menu of options 
  - Start, Stop, Restart, Reload, Delete
- Create page to add embedded cartridges

**Comment by jyore** [comment]
Closing this ticket since the management is there, will open a new issue for creating the page to add new cartridges
