### ISSUE TITLE
Create Overall User Interface

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#2]
Create an overall user interface design for the application

This should include the following
- Color scheme and fonts
- Menu layout

The owner of this task can improve on existing designs and add additional requirements as they see fit

**Comment by jyore** [comment]
I suggest using black/red/white/grey scheme to match OpenShift/Red Hat.

For the menu, I'd try to make it feel similar to the OpenShift webapp, just mobile-ified

**Comment by jyore** [comment]
I think this is mostly covered for now and there are a couple other issues that handle smaller details of this. 

I'm going to close it as it is too broad and mostly done for the alpha release anyway.
