### ISSUE TITLE
Improve Strategy for Storing User Credentials

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#3]
A users' account and password are vital to this application as they are sent as part of each REST request. Currently, account and password are stored within the Android Shared Preferences framework. In addition, these values are stored in plain text.

Improve the existing implementation by encrypting sensitive data or choosing an alternate strategy altogether.

**Comment by jyore** [comment]
@jzintak, when is this gonna happen? We are making good progress on getting to our alpha release and this should added for that release
