### ISSUE TITLE
Implement Continuous Integration Environment

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#6]
Implement a continuous integration environment for the project. It should have the following features:
- Pull code and build upon each commit
- GitHub Integration
- Links/Commits
- Authentication into environment

**Comment by jyore** [comment]
- Pulls code from github
- Builds on commit
- GitHub OAUTH integration

Check it out at its temporary location:
http://jenkins.jyore.com/jenkins

**Comment by jyore** [comment]
as we have gotten our first successful build in Jenkins, I am closing issue.

**Comment by jyore** [comment]
Moved to new temporary url:

http://jboss.jyore.com/jenkins
