### ISSUE TITLE
Provide a method to invalidate the cache

### ISSUE THREAD

**Issue by sabre1041** [sabre1041/openshift-android#9]
Implement functionality to invalidate the cache. This will be used when users log out of the application and switch accounts. 

Provide two methods of cache invalidation
- Targeted entities
- Entire collection

**Comment by jyore** [comment]
Will put up one to remove a certain entry soon. To do the remove all, I need to go into the underlying APIs and provide a method to get a collection of keys to iterate over and remove.

**Comment by jyore** [comment]
Since the framework changed and the caching changed, the invalidation will now happen differently. Because of this I am closing as it is a duplicate of another feature being worked on.

duplicates #11
